trajectory_eval_distance:
  min_dist_cat: 8
  max_dist_cat: 8
trajectory_eval_len_traj_pred: 6
trajectory_eval_context_size: 2
traj_stride: 8

# distance bounds for distance and action and distance predictions 
eval_distance:
  eval_min_dist_cat: -64
  eval_max_dist_cat: 64
eval_len_traj_pred: 6
eval_context_size: 1

eval_datasets:
  wohuman_vln:
    data_folder: data/wohuman_vln
    train: data_splits/wohuman_vln/train # path to train folder with traj_names.txt
    test: data_splits/wohuman_vln/test # path to test folder with traj_names.txt
    goals_per_obs: 1
    instruction_file: data_splits/wohuman_vln/instructions.json
