trajectory_eval_distance:
  min_dist_cat: 8
  max_dist_cat: 8
trajectory_eval_len_traj_pred: 6
trajectory_eval_context_size: 2
traj_stride: 8

# distance bounds for distance and action and distance predictions 
eval_distance:
  eval_min_dist_cat: -64
  eval_max_dist_cat: 64
eval_len_traj_pred: 6
eval_context_size: 2

eval_datasets:
  ha_vln:
    data_folder: data/ha_vln
    train: data_splits/ha_vln/train # path to train folder with traj_names.txt
    test: data_splits/ha_vln/test # path to test folder with traj_names.txt
    goals_per_obs: 2
    instruction_file: data_splits/ha_vln/instructions.json
